package btools.router.known;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import btools.router.OsmNodeNamed;
import btools.router.OsmTrack;
import btools.router.RoundTripQualityGate;
import btools.router.RoundTripQualityGate.HostileStretch;
import btools.router.RoutingContext;
import btools.router.RoutingEngine;

import org.junit.Assert;
import org.junit.Assume;
import org.junit.Test;

/**
 * GPX replay tests — sample waypoints from known-good Komoot routes
 * and feed them to brouter as point-to-point waypoints (not round-trip).
 * Isolates the routing engine from the round-trip planner:
 *   - PASS means brouter's fastbike profile and routing engine can
 *     reproduce Komoot's road choices given the right waypoints; the
 *     round-trip planner's candidate placement is the bottleneck.
 *   - FAIL means brouter's engine traverses hostile content even when
 *     told to go through Komoot's waypoints; the fastbike profile
 *     cost-function is the bottleneck.
 *
 * Generated by {@code tools/replay-gpx-via-brouter.mjs} from
 * {@code tmp/gpx/innsbruck/*.gpx}.
 */
public class GpxReplayInvestigation {

  private File profileFile(String name) {
    File p = new File("misc/profiles2/" + name + ".brf");
    if (!p.exists()) p = new File("../misc/profiles2/" + name + ".brf");
    return p.exists() ? p : null;
  }

  /**
   * Replay of Komoot "Leutasch-Schild – Ginzens–Sellrain Panoramastraße Runde von Alpenzoo" — feeds the
   * sampled waypoints to brouter and reports whether the resulting
   * point-to-point route is clean enough to satisfy the round-trip
   * quality gate. Failure means the routing engine (with the
   * fastbike profile) can't reproduce the known-good Komoot route
   * even when given the right waypoints.
   */
  @Test
  public void replay_2026_05_27_2989519890_GPX_Download_Leutasch_Schild_Ginzens_S() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment present", segFile.exists());
    File pf = profileFile("fastbike");
    Assume.assumeTrue("profile present", pf != null);

    List<OsmNodeNamed> wplist = new ArrayList<>();
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "from"; n.ilon = 191400609; n.ilat = 137282375; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via1"; n.ilon = 191199156; n.ilat = 137281012; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via2"; n.ilon = 191163447; n.ilat = 137372370; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via3"; n.ilon = 191110627; n.ilat = 137316535; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via4"; n.ilon = 191245350; n.ilat = 137239277; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "to"; n.ilon = 191306100; n.ilat = 137236952; wplist.add(n); }

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = pf.getAbsolutePath();
    RoutingEngine re = new RoutingEngine(null, null, segDir, wplist, rctx);
    re.quite = true;
    re.doRun(0);

    String err = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    System.out.println("=== replay_2026_05_27_2989519890_GPX_Download_Leutasch_Schild_Ginzens_S ===");
    System.out.println("  error: " + (err == null ? "PASSED" : err));
    if (track != null && track.nodes != null) {
      System.out.println("  route: " + track.distance + "m / " + track.nodes.size() + " nodes");
      HostileStretch hs = RoundTripQualityGate.worstHostileStretchPaved(track);
      if (hs.isPresent()) {
        System.out.printf("  worst-hostile: %dm at (%.6f, %.6f) tags: %s%n",
          hs.meters, hs.startLat(), hs.startLon(), hs.startTags);
      } else {
        System.out.println("  hostile: none");
      }
      Assert.assertNull("expected clean point-to-point route through Komoot waypoints: " + err, err);
      Assert.assertTrue("expected no hostile stretch over the gate cap",
        !hs.isPresent() || hs.meters <= RoundTripQualityGate.MAX_CONTIGUOUS_HOSTILE_METERS);
    } else {
      Assert.fail("brouter returned no track: " + err);
    }
  }

  /**
   * Replay of Komoot "Notburga-Steg – Reintaler See Runde von Hall-Thaur" — feeds the
   * sampled waypoints to brouter and reports whether the resulting
   * point-to-point route is clean enough to satisfy the round-trip
   * quality gate. Failure means the routing engine (with the
   * fastbike profile) can't reproduce the known-good Komoot route
   * even when given the right waypoints.
   */
  @Test
  public void replay_2026_05_27_2989520649_GPX_Download_Notburga_Steg_Reintaler_S() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment present", segFile.exists());
    File pf = profileFile("fastbike");
    Assume.assumeTrue("profile present", pf != null);

    List<OsmNodeNamed> wplist = new ArrayList<>();
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "from"; n.ilon = 191474002; n.ilat = 137277082; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via1"; n.ilon = 191665224; n.ilat = 137314694; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via2"; n.ilon = 191872088; n.ilat = 137429131; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via3"; n.ilon = 191958901; n.ilat = 137477078; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via4"; n.ilon = 191800382; n.ilat = 137404795; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "to"; n.ilon = 191638466; n.ilat = 137315887; wplist.add(n); }

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = pf.getAbsolutePath();
    RoutingEngine re = new RoutingEngine(null, null, segDir, wplist, rctx);
    re.quite = true;
    re.doRun(0);

    String err = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    System.out.println("=== replay_2026_05_27_2989520649_GPX_Download_Notburga_Steg_Reintaler_S ===");
    System.out.println("  error: " + (err == null ? "PASSED" : err));
    if (track != null && track.nodes != null) {
      System.out.println("  route: " + track.distance + "m / " + track.nodes.size() + " nodes");
      HostileStretch hs = RoundTripQualityGate.worstHostileStretchPaved(track);
      if (hs.isPresent()) {
        System.out.printf("  worst-hostile: %dm at (%.6f, %.6f) tags: %s%n",
          hs.meters, hs.startLat(), hs.startLon(), hs.startTags);
      } else {
        System.out.println("  hostile: none");
      }
      Assert.assertNull("expected clean point-to-point route through Komoot waypoints: " + err, err);
      Assert.assertTrue("expected no hostile stretch over the gate cap",
        !hs.isPresent() || hs.meters <= RoundTripQualityGate.MAX_CONTIGUOUS_HOSTILE_METERS);
    } else {
      Assert.fail("brouter returned no track: " + err);
    }
  }

  /**
   * Replay of Komoot "Leutasch-Schild – Ginzens–Sellrain Panoramastraße Runde von Alpenzoo" — feeds the
   * sampled waypoints to brouter and reports whether the resulting
   * point-to-point route is clean enough to satisfy the round-trip
   * quality gate. Failure means the routing engine (with the
   * fastbike profile) can't reproduce the known-good Komoot route
   * even when given the right waypoints.
   */
  @Test
  public void replay_2026_05_27_2989521788_GPX_Download_Leutasch_Schild_Ginzens_S() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment present", segFile.exists());
    File pf = profileFile("fastbike");
    Assume.assumeTrue("profile present", pf != null);

    List<OsmNodeNamed> wplist = new ArrayList<>();
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "from"; n.ilon = 191400609; n.ilat = 137282375; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via1"; n.ilon = 191199156; n.ilat = 137281012; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via2"; n.ilon = 191163447; n.ilat = 137372370; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via3"; n.ilon = 191110627; n.ilat = 137316535; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via4"; n.ilon = 191245350; n.ilat = 137239277; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "to"; n.ilon = 191306100; n.ilat = 137236952; wplist.add(n); }

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = pf.getAbsolutePath();
    RoutingEngine re = new RoutingEngine(null, null, segDir, wplist, rctx);
    re.quite = true;
    re.doRun(0);

    String err = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    System.out.println("=== replay_2026_05_27_2989521788_GPX_Download_Leutasch_Schild_Ginzens_S ===");
    System.out.println("  error: " + (err == null ? "PASSED" : err));
    if (track != null && track.nodes != null) {
      System.out.println("  route: " + track.distance + "m / " + track.nodes.size() + " nodes");
      HostileStretch hs = RoundTripQualityGate.worstHostileStretchPaved(track);
      if (hs.isPresent()) {
        System.out.printf("  worst-hostile: %dm at (%.6f, %.6f) tags: %s%n",
          hs.meters, hs.startLat(), hs.startLon(), hs.startTags);
      } else {
        System.out.println("  hostile: none");
      }
      Assert.assertNull("expected clean point-to-point route through Komoot waypoints: " + err, err);
      Assert.assertTrue("expected no hostile stretch over the gate cap",
        !hs.isPresent() || hs.meters <= RoundTripQualityGate.MAX_CONTIGUOUS_HOSTILE_METERS);
    } else {
      Assert.fail("brouter returned no track: " + err);
    }
  }

  /**
   * Replay of Komoot "Axamer Plateau – Natters Runde von Innsbruck Messe" — feeds the
   * sampled waypoints to brouter and reports whether the resulting
   * point-to-point route is clean enough to satisfy the round-trip
   * quality gate. Failure means the routing engine (with the
   * fastbike profile) can't reproduce the known-good Komoot route
   * even when given the right waypoints.
   */
  @Test
  public void replay_2026_05_27_2989522065_GPX_Download_Axamer_Plateau_Natters_Ru() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment present", segFile.exists());
    File pf = profileFile("fastbike");
    Assume.assumeTrue("profile present", pf != null);

    List<OsmNodeNamed> wplist = new ArrayList<>();
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "from"; n.ilon = 191406971; n.ilat = 137272821; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via1"; n.ilon = 191212461; n.ilat = 137280459; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via2"; n.ilon = 191145684; n.ilat = 137283356; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via3"; n.ilon = 191290600; n.ilat = 137232660; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "via4"; n.ilon = 191432162; n.ilat = 137258638; wplist.add(n); }
    { OsmNodeNamed n = new OsmNodeNamed(); n.name = "to"; n.ilon = 191528237; n.ilat = 137290833; wplist.add(n); }

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = pf.getAbsolutePath();
    RoutingEngine re = new RoutingEngine(null, null, segDir, wplist, rctx);
    re.quite = true;
    re.doRun(0);

    String err = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    System.out.println("=== replay_2026_05_27_2989522065_GPX_Download_Axamer_Plateau_Natters_Ru ===");
    System.out.println("  error: " + (err == null ? "PASSED" : err));
    if (track != null && track.nodes != null) {
      System.out.println("  route: " + track.distance + "m / " + track.nodes.size() + " nodes");
      HostileStretch hs = RoundTripQualityGate.worstHostileStretchPaved(track);
      if (hs.isPresent()) {
        System.out.printf("  worst-hostile: %dm at (%.6f, %.6f) tags: %s%n",
          hs.meters, hs.startLat(), hs.startLon(), hs.startTags);
      } else {
        System.out.println("  hostile: none");
      }
      Assert.assertNull("expected clean point-to-point route through Komoot waypoints: " + err, err);
      Assert.assertTrue("expected no hostile stretch over the gate cap",
        !hs.isPresent() || hs.meters <= RoundTripQualityGate.MAX_CONTIGUOUS_HOSTILE_METERS);
    } else {
      Assert.fail("brouter returned no track: " + err);
    }
  }


}
