package btools.router.known;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import btools.router.OsmNodeNamed;
import btools.router.OsmTrack;
import btools.router.RoundTripAlgorithm;
import btools.router.RoutingContext;
import btools.router.RoutingEngine;

import org.junit.Assert;
import org.junit.Assume;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Known-failure sentinels for round-trip routing. Each method is
 * @Ignored while the defect reproduces; removing the @Ignore when the
 * underlying fix lands lets the test turn green and proves the failure
 * is gone. Generated by {@code tools/generate-failing-tests.mjs} from
 * the cached Phase 2 v3 measurement.
 *
 * <p>These tests opt in via {@code -Dloop.tests=true} and require
 * segment data + profiles, same as {@code LoopQualityTest}.
 */
public class LoopKnownFailuresTest {

  private File profileFile(String name) {
    File p = new File("misc/profiles2/" + name + ".brf");
    if (!p.exists()) p = new File("../misc/profiles2/" + name + ".brf");
    return p.exists() ? p : null;
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, fastbike profile,
   * direction N (0°), greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 0, radius 15900m, shape=INVALID_RETRACE): contiguous 13907m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmFastbikeNViaGreedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, fastbike profile,
   * direction N (0°), iso_greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 0, radius 15900m, shape=INVALID_RETRACE): contiguous 13907m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmFastbikeNViaIso_greedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISO_GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, fastbike profile,
   * direction N (0°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 0, radius 15900m, shape=INVALID_RETRACE): contiguous 17559m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmFastbikeNViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: DREIEICH loop, 100 km, fastbike profile,
   * direction N (0°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 0, radius 15900m, shape=INVALID_RETRACE): contiguous 1525m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich100kmFastbikeNViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: DREIEICH loop, 100 km, fastbike profile,
   * direction W (270°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 270, radius 15900m, shape=INVALID_RETRACE): contiguous 1525m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich100kmFastbikeWViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 270;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: COASTAL_NICE loop, 50 km, fastbike profile,
   * direction N (0°), probe variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 0, radius 8000m, shape=INVALID_RETRACE): contiguous 1843m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void coastalNice50kmFastbikeNViaProbe() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E5_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 187278160;
    start.ilat = 133694440;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 7958;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.WAYPOINT;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 25000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: COASTAL_NICE loop, 75 km, fastbike profile,
   * direction N (0°), greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 0, radius 11937m, shape=INVALID_RETRACE): contiguous 1843m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void coastalNice75kmFastbikeNViaGreedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E5_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 187278160;
    start.ilat = 133694440;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 11937;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 37500);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: COASTAL_NICE loop, 75 km, fastbike profile,
   * direction N (0°), probe variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 0, radius 11937m, shape=INVALID_RETRACE): contiguous 1843m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void coastalNice75kmFastbikeNViaProbe() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E5_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 187278160;
    start.ilat = 133694440;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 11937;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.WAYPOINT;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 37500);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: DREIEICH loop, 75 km, fastbike profile,
   * direction W (270°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 270, radius 11937m, shape=INVALID_RETRACE): contiguous 1854m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich75kmFastbikeWViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 270;
    rctx.roundTripDistance = 11937;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 37500);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: RURAL_LOZERE loop, 30 km, fastbike profile,
   * direction E (90°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 4800m, shape=INVALID_RETRACE): contiguous 2011m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void ruralLozere30kmFastbikeEViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E0_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 183440000;
    start.ilat = 134460000;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 4775;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 15000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: RURAL_LOZERE loop, 30 km, fastbike profile,
   * direction S (180°), greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 180, radius 4800m, shape=INVALID_RETRACE): contiguous 2011m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void ruralLozere30kmFastbikeSViaGreedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E0_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 183440000;
    start.ilat = 134460000;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 180;
    rctx.roundTripDistance = 4775;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 15000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: RURAL_LOZERE loop, 30 km, fastbike profile,
   * direction S (180°), iso_greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 180, radius 4800m, shape=INVALID_RETRACE): contiguous 2011m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void ruralLozere30kmFastbikeSViaIso_greedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E0_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 183440000;
    start.ilat = 134460000;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 180;
    rctx.roundTripDistance = 4775;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISO_GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 15000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: RURAL_LOZERE loop, 30 km, fastbike profile,
   * direction S (180°), probe variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 180, radius 4800m, shape=INVALID_RETRACE): contiguous 2011m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void ruralLozere30kmFastbikeSViaProbe() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E0_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 183440000;
    start.ilat = 134460000;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 180;
    rctx.roundTripDistance = 4775;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.WAYPOINT;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 15000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: RURAL_LOZERE loop, 50 km, fastbike profile,
   * direction E (90°), greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 8000m, shape=INVALID_RETRACE): contiguous 2011m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void ruralLozere50kmFastbikeEViaGreedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E0_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 183440000;
    start.ilat = 134460000;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 7958;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 25000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: RURAL_LOZERE loop, 50 km, fastbike profile,
   * direction E (90°), iso_greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 8000m, shape=INVALID_RETRACE): contiguous 2011m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void ruralLozere50kmFastbikeEViaIso_greedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E0_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 183440000;
    start.ilat = 134460000;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 7958;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISO_GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 25000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: RURAL_LOZERE loop, 50 km, fastbike profile,
   * direction E (90°), probe variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 8000m, shape=INVALID_RETRACE): contiguous 2011m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void ruralLozere50kmFastbikeEViaProbe() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E0_N40.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 183440000;
    start.ilat = 134460000;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 7958;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.WAYPOINT;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 25000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: DREIEICH loop, 100 km, fastbike profile,
   * direction W (270°), greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 270, radius 15900m, shape=INVALID_RETRACE): contiguous 2140m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich100kmFastbikeWViaGreedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 270;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: DREIEICH loop, 100 km, fastbike profile,
   * direction W (270°), probe variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 270, radius 15900m, shape=INVALID_RETRACE): contiguous 2140m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich100kmFastbikeWViaProbe() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 270;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.WAYPOINT;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: DREIEICH loop, 30 km, fastbike profile,
   * direction S (180°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 180, radius 4800m, shape=INVALID_RETRACE): contiguous 2219m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich30kmFastbikeSViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 180;
    rctx.roundTripDistance = 4775;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 15000);
  }

  /**
   * KNOWN FAILURE — planner committed a leg with a contiguous off-road stretch above the 1500 m cap.
   *
   * Scenario: DREIEICH loop, 30 km, fastbike profile,
   * direction E (90°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 4800m, shape=INVALID_RETRACE): contiguous 2232m of profile-hostile way (max 1500m) — single off-road stretch too long for road bike}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: contiguous-hostile-stretch (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich30kmFastbikeEViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 4775;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 15000);
  }

  /**
   * KNOWN FAILURE — reuse classifier flagged the loop as INVALID_RETRACE.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, fastbike profile,
   * direction S (180°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 180, radius 15900m, shape=INVALID_RETRACE): route has 21 self-intersections (max 15) — chaotic loop geometry}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: shape-invalid-retrace (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmFastbikeSViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 180;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — reuse classifier flagged the loop as INVALID_RETRACE.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, fastbike profile,
   * direction W (270°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 270, radius 15900m, shape=INVALID_RETRACE): route has 33 self-intersections (max 15) — chaotic loop geometry}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: shape-invalid-retrace (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmFastbikeWViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 270;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — reuse classifier flagged the loop as INVALID_RETRACE.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, gravel profile,
   * direction E (90°), isochrone variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 15900m, shape=INVALID_RETRACE): route has 53 self-intersections (max 15) — chaotic loop geometry}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: shape-invalid-retrace (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmGravelEViaIsochrone() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("gravel");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISOCHRONE;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — route length falls outside the [0.5, 1.8] ratio band relative to requested.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, gravel profile,
   * direction N (0°), probe variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 0, radius 15900m, shape=INVALID_RETRACE): distance ratio 2.40 outside [0.5, 1.8]}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: distance-ratio (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmGravelNViaProbe() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("gravel");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.WAYPOINT;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — route length falls outside the [0.5, 1.8] ratio band relative to requested.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, gravel profile,
   * direction E (90°), greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 15900m, shape=INVALID_RETRACE): distance ratio 1.84 outside [0.5, 1.8]}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: distance-ratio (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmGravelEViaGreedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("gravel");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — route length falls outside the [0.5, 1.8] ratio band relative to requested.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 100 km, gravel profile,
   * direction E (90°), iso_greedy variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 15900m, shape=INVALID_RETRACE): distance ratio 1.84 outside [0.5, 1.8]}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: distance-ratio (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck100kmGravelEViaIso_greedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("gravel");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISO_GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — uncategorized — needs human triage.
   *
   * Scenario: ALPINE_INNSBRUCK loop, 75 km, gravel profile,
   * direction N (0°), probe variant.
   *
   * <p>Current rejection: {@code Index 0 out of bounds for length 0}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: other (auto-generated by tools/generate-failing-tests.mjs)")
  public void alpineInnsbruck75kmGravelNViaProbe() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N45.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("gravel");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 191461700;
    start.ilat = 137282800;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 11937;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.WAYPOINT;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 37500);
  }

  /**
   * KNOWN FAILURE — uncategorized — needs human triage.
   *
   * Scenario: DREIEICH loop, 100 km, fastbike profile,
   * direction N (0°), greedy variant.
   *
   * <p>Current rejection: {@code round-trip could not place enough waypoints to form a loop (need 2 intermediate, got 0) for direction 0 at radius 15900m}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: other (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich100kmFastbikeNViaGreedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — uncategorized — needs human triage.
   *
   * Scenario: DREIEICH loop, 100 km, fastbike profile,
   * direction N (0°), iso_greedy variant.
   *
   * <p>Current rejection: {@code round-trip could not place enough waypoints to form a loop (need 2 intermediate, got 0) for direction 0 at radius 15900m}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: other (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich100kmFastbikeNViaIso_greedy() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 0;
    rctx.roundTripDistance = 15915;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.ISO_GREEDY;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 50000);
  }

  /**
   * KNOWN FAILURE — route uses more than 10% off-road edges on a paved profile.
   *
   * Scenario: DREIEICH loop, 30 km, fastbike profile,
   * direction E (90°), probe variant.
   *
   * <p>Current rejection: {@code round-trip rejected by quality gate (direction 90, radius 4800m, shape=INVALID_RETRACE): 19% of distance on profile-hostile ways (max 10%) — route uses path/track/unpaved that a road bike should avoid}
   *
   * <p>This test is @Ignored while the defect is known. Remove the
   * @Ignore when the underlying fix lands; the assertion expects the
   * router to PRODUCE a valid loop, so the test will turn green
   * automatically when the failure stops reproducing.
   */
  @Test
  @Ignore("known-failure: hostile-fraction (auto-generated by tools/generate-failing-tests.mjs)")
  public void dreieich30kmFastbikeEViaProbe() throws Exception {
    Assume.assumeTrue("loop-tests opt-in", Boolean.getBoolean("loop.tests"));
    File segDir = new File("../segments4");
    if (!segDir.exists()) segDir = new File("segments4");
    File segFile = new File(segDir, "E10_N50.rd5");
    Assume.assumeTrue("segment file present: " + segFile.getAbsolutePath(), segFile.exists());
    File profileFile = profileFile("fastbike");
    Assume.assumeTrue("profile present: " + profileFile, profileFile != null && profileFile.exists());

    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = 188661500;
    start.ilat = 140042500;
    wplist.add(start);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = profileFile.getAbsolutePath();
    rctx.startDirection = 90;
    rctx.roundTripDistance = 4775;
    rctx.roundTripAlgorithm = RoundTripAlgorithm.WAYPOINT;

    RoutingEngine re = new RoutingEngine(
      null, null, segDir, wplist, rctx,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.doRun(0);

    String error = re.getErrorMessage();
    OsmTrack track = re.getFoundTrack();
    Assert.assertNull("expected loop to succeed (defect fixed): " + error, error);
    Assert.assertNotNull("expected non-null track", track);
    Assert.assertTrue("expected reasonable distance", track.distance >= 15000);
  }

}
