package btools.router;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

/**
 * Integration tests for gradient computation using the Dreieich test data.
 * Depends on segment files generated by brouter-map-creator:test.
 */
public class GradientIntegrationTest {
  private static final String PROFILE_PATH = "/../../../../misc/profiles2/trekking.brf";
  private static final String SEGMENTS_PATH = "/../../../../brouter-map-creator/build/resources/test/tmp/segments";

  private String workingDir;

  @Before
  public void before() {
    URL resulturl = this.getClass().getResource("/testtrack0.gpx");
    Assert.assertNotNull("reference result not found", resulturl);
    File resultfile = new File(resulturl.getFile());
    workingDir = resultfile.getParentFile().getAbsolutePath();
  }

  @Test
  public void routedTrackContainsGradientInMessages() {
    OsmTrack track = calcRoute(8.720897, 50.002515, 8.723658, 49.997510);
    Assert.assertNotNull("track should not be null", track);

    List<String> messages = track.aggregateMessages();
    Assert.assertTrue("track should have messages", messages.size() > 0);

    for (String msg : messages) {
      String[] cols = msg.split("\t");
      Assert.assertEquals("message should have 14 columns (including Gradient)", 14, cols.length);
      // Gradient column (index 13) should be a parseable integer
      try {
        Integer.parseInt(cols[13]);
      } catch (NumberFormatException e) {
        Assert.fail("gradient column should be an integer, got: " + cols[13]);
      }
    }
  }

  @Test
  public void gradientValuesAreReasonable() {
    OsmTrack track = calcRoute(8.720897, 50.002515, 8.723658, 49.997510);
    Assert.assertNotNull(track);

    List<MessageData> segments = track.aggregateMessageData();
    for (MessageData md : segments) {
      // Dreieich is relatively flat (~100-120m elevation). Gradients should be within reason.
      Assert.assertTrue("gradient " + md.gradient + "% is unreasonably steep (> 30%)",
        Math.abs(md.gradient) <= 30.0f);
      // Distance should be positive
      Assert.assertTrue("segment distance should be positive", md.linkdist > 0);
    }
  }

  @Test
  public void gradientConsistentWithElevationAndDistance() {
    OsmTrack track = calcRoute(8.723037, 50.000491, 8.712737, 50.002899);
    Assert.assertNotNull(track);

    List<MessageData> segments = track.aggregateMessageData();
    for (MessageData md : segments) {
      if (md.linkdist > 0) {
        float expectedGradient = (float) (md.deltaH / md.linkdist * 100.0);
        Assert.assertEquals("gradient should match deltaH/dist*100",
          expectedGradient, md.gradient, 0.01f);
      }
    }
  }

  @Test
  public void filterSegmentsOnRealRoute() {
    OsmTrack track = calcRoute(8.720897, 50.002515, 8.723658, 49.997510);
    Assert.assertNotNull(track);

    List<String> allMessages = track.aggregateMessages();
    int totalCount = allMessages.size();

    // Filter for segments with any gradient at all (> 0.1%)
    List<String> withGradient = track.filterSegments(-1, -1, 0.1f, -1);
    // Some segments should have gradient, some may be flat
    Assert.assertTrue("at least some segments should have gradient > 0.1%",
      withGradient.size() > 0);
    Assert.assertTrue("filtered count should be <= total",
      withGradient.size() <= totalCount);
  }

  @Test
  public void filterByLengthOnRealRoute() {
    OsmTrack track = calcRoute(8.720897, 50.002515, 8.723658, 49.997510);
    Assert.assertNotNull(track);

    // Get all segments and find the longest
    List<MessageData> allSegments = track.aggregateMessageData();
    int maxDist = 0;
    for (MessageData md : allSegments) {
      if (md.linkdist > maxDist) maxDist = md.linkdist;
    }

    // Filter for very long segments - should get fewer results
    List<String> longOnly = track.filterSegments(maxDist, -1, -1, -1);
    Assert.assertTrue("long filter should return fewer or equal segments",
      longOnly.size() <= allSegments.size());
    Assert.assertTrue("at least the longest segment should match",
      longOnly.size() >= 1);

    // Filter for impossibly long segments - should get nothing
    List<String> tooLong = track.filterSegments(maxDist + 1, -1, -1, -1);
    Assert.assertEquals("filter beyond max distance should return nothing", 0, tooLong.size());
  }

  @Test
  public void getFilteredMessagesWithParamsOnRealRoute() {
    OsmTrack track = calcRoute(8.720897, 50.002515, 8.723658, 49.997510);
    Assert.assertNotNull(track);

    List<String> unfilteredMessages = track.getFilteredMessages();
    int unfilteredCount = unfilteredMessages.size();

    // Set a length filter
    track.segmentFilterMinLength = 100;
    List<String> filteredMessages = track.getFilteredMessages();

    Assert.assertTrue("filtered with minLength=100 should return <= total",
      filteredMessages.size() <= unfilteredCount);
  }

  @Test
  public void aggregateMessageDataMatchesAggregateMessages() {
    OsmTrack track = calcRoute(8.723037, 50.000491, 8.712737, 50.002899);
    Assert.assertNotNull(track);

    List<MessageData> dataList = track.aggregateMessageData();
    List<String> messageList = track.aggregateMessages();

    Assert.assertEquals("aggregateMessageData and aggregateMessages should have same count",
      messageList.size(), dataList.size());

    // Each MessageData.toMessage() should match the corresponding string
    for (int i = 0; i < dataList.size(); i++) {
      Assert.assertEquals("message " + i + " should match",
        messageList.get(i), dataList.get(i).toMessage());
    }
  }

  private OsmTrack calcRoute(double flon, double flat, double tlon, double tlat) {
    List<OsmNodeNamed> wplist = new ArrayList<>();
    OsmNodeNamed from = new OsmNodeNamed();
    from.name = "from";
    from.ilon = 180000000 + (int) (flon * 1000000 + 0.5);
    from.ilat = 90000000 + (int) (flat * 1000000 + 0.5);
    wplist.add(from);

    OsmNodeNamed to = new OsmNodeNamed();
    to.name = "to";
    to.ilon = 180000000 + (int) (tlon * 1000000 + 0.5);
    to.ilat = 90000000 + (int) (tlat * 1000000 + 0.5);
    wplist.add(to);

    RoutingContext rctx = new RoutingContext();
    rctx.localFunction = workingDir + PROFILE_PATH;

    RoutingEngine re = new RoutingEngine(
      null, null,
      new File(workingDir, SEGMENTS_PATH),
      wplist, rctx);
    re.doRun(0);

    Assert.assertNull("routing should succeed: " + re.getErrorMessage(), re.getErrorMessage());
    return re.getFoundTrack();
  }
}
