package btools.router;

import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.function.Consumer;

/**
 * Shared setup and assertions for round-trip tests against the bundled Dreieich
 * fixture (generated by the map-creator test into build/resources, version-consistent
 * with misc/profiles2). No downloads required, so these run in CI.
 */
final class RoundTripFixture {

  static final int START_ILON = 188720000; // 8.72E (Dreieich)
  static final int START_ILAT = 140000000; // 50.0N

  // Structural-invariant thresholds for a valid loop (strict, with margin over observed behaviour).
  private static final int MIN_LOOP_NODES = 10;
  private static final int MAX_CLOSURE_M = 100;
  private static final int MAX_SEGMENT_M = 1500;

  private static final File PROJECT_DIR = resolveProjectDir();

  private RoundTripFixture() {
  }

  private static File resolveProjectDir() {
    try {
      return new File(".").getCanonicalFile().getParentFile();
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  static File projectDir() {
    return PROJECT_DIR;
  }

  static File segmentDir() {
    return new File(projectDir(), "brouter-map-creator/build/resources/test/tmp/segments");
  }

  static File profileFile(String name) {
    return new File(projectDir(), "misc/profiles2/" + name + ".brf");
  }

  /** A round-trip start/via node at the given lon/lat. */
  static OsmNodeNamed node(String name, double lon, double lat) {
    OsmNodeNamed n = new OsmNodeNamed();
    n.name = name;
    n.ilon = 180000000 + (int) (lon * 1000000 + 0.5);
    n.ilat = 90000000 + (int) (lat * 1000000 + 0.5);
    return n;
  }

  static RoutingEngine engine(String profile, int direction, int radius) {
    return engine(profile, direction, radius, rc -> { });
  }

  /**
   * Build and run a round-trip engine from the Dreieich origin, applying {@code tweak}
   * to the context and appending any {@code vias} as intermediate waypoints.
   */
  static RoutingEngine engine(String profile, int direction, int radius,
                              Consumer<RoutingContext> tweak, OsmNodeNamed... vias) {
    List<OsmNodeNamed> wps = new ArrayList<>();
    wps.add(node("from", 8.72, 50.0));
    for (OsmNodeNamed via : vias) {
      wps.add(via);
    }

    RoutingContext rc = new RoutingContext();
    rc.localFunction = profileFile(profile).getAbsolutePath();
    rc.startDirection = direction;
    rc.roundTripDistance = radius;
    rc.turnInstructionMode = 2; // generate voice hints so they can be validated
    tweak.accept(rc);

    RoutingEngine re = new RoutingEngine(null, null, segmentDir(), wps, rc,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.quite = true;
    re.doRun(0);
    return re;
  }

  /** Convenience: the found track (may be null on failure). */
  static OsmTrack route(String profile, int direction, int radius) {
    return engine(profile, direction, radius).getFoundTrack();
  }

  /**
   * Assert the structural invariants of a valid round-trip loop: non-degenerate,
   * closes near origin, no beeline segments or BL hints, bounded road reuse, and
   * sane voice hints. The voice-hint check is the regression guard for the
   * origin-chain bug that produced negative indices / out-of-range seam angles.
   * {@code maxReusePct} is relaxed for same-way-back loops which intentionally retrace.
   */
  static void assertValidLoop(OsmTrack track, String label, double maxReusePct) {
    org.junit.Assert.assertNotNull(label + ": no track", track);
    List<OsmPathElement> nodes = track.nodes;
    org.junit.Assert.assertTrue(label + ": degenerate loop (" + nodes.size() + " nodes)",
      nodes.size() >= MIN_LOOP_NODES);

    int closing = nodes.get(0).calcDistance(nodes.get(nodes.size() - 1));
    org.junit.Assert.assertTrue(label + ": loop does not close, gap " + closing + "m",
      closing <= MAX_CLOSURE_M);

    int total = 0, reused = 0, maxSeg = 0;
    Set<Long> edges = new HashSet<>();
    long prevId = nodes.get(0).getIdFromPos();
    for (int i = 1; i < nodes.size(); i++) {
      long id = nodes.get(i).getIdFromPos();
      int d = nodes.get(i).calcDistance(nodes.get(i - 1));
      total += d;
      if (d > maxSeg) maxSeg = d;
      long edge = Math.min(prevId, id) * 1_000_003L + Math.max(prevId, id);
      if (!edges.add(edge)) reused += d;
      prevId = id;
    }
    org.junit.Assert.assertTrue(label + ": beeline segment " + maxSeg + "m", maxSeg <= MAX_SEGMENT_M);
    double reusePct = total > 0 ? 100.0 * reused / total : 0;
    org.junit.Assert.assertTrue(label + ": road reuse " + (int) reusePct + "% > " + (int) maxReusePct + "%",
      reusePct <= maxReusePct);

    if (track.voiceHints != null) {
      for (VoiceHint h : track.voiceHints.list) {
        org.junit.Assert.assertTrue(label + ": voice hint index " + h.indexInTrack + " out of range",
          h.indexInTrack >= 0 && h.indexInTrack < nodes.size());
        org.junit.Assert.assertNotEquals(label + ": unexpected beeline hint", VoiceHint.BL, h.cmd);
        if (!h.isRoundabout()) { // roundabout angle is cumulative rotation, legitimately > 180
          org.junit.Assert.assertTrue(label + ": voice hint angle " + h.angle + " out of [-180,180]",
            h.angle >= -180f && h.angle <= 180f);
        }
      }
    }
  }
}
