package btools.router;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * Shared setup for round-trip tests against the bundled Dreieich fixture
 * (generated by the map-creator test into build/resources, version-consistent
 * with misc/profiles2). No downloads required, so these run in CI.
 */
final class RoundTripFixture {

  static final int START_ILON = 188720000; // 8.72E (Dreieich)
  static final int START_ILAT = 140000000; // 50.0N

  private RoundTripFixture() {
  }

  static File projectDir() {
    try {
      return new File(".").getCanonicalFile().getParentFile();
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  static File segmentDir() {
    return new File(projectDir(), "brouter-map-creator/build/resources/test/tmp/segments");
  }

  static File profileFile(String name) {
    return new File(projectDir(), "misc/profiles2/" + name + ".brf");
  }

  /** Build and run a round-trip engine from the Dreieich origin. */
  static RoutingEngine engine(String profile, int direction, int radius) {
    List<OsmNodeNamed> wps = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = START_ILON;
    start.ilat = START_ILAT;
    wps.add(start);

    RoutingContext rc = new RoutingContext();
    rc.localFunction = profileFile(profile).getAbsolutePath();
    rc.startDirection = direction;
    rc.roundTripDistance = radius;
    rc.turnInstructionMode = 2; // generate voice hints so they can be validated

    RoutingEngine re = new RoutingEngine(null, null, segmentDir(), wps, rc,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.quite = true;
    re.doRun(0);
    return re;
  }

  /** Convenience: the found track (may be null on failure). */
  static OsmTrack route(String profile, int direction, int radius) {
    return engine(profile, direction, radius).getFoundTrack();
  }

  /**
   * Assert the structural invariants of a valid round-trip loop: non-degenerate,
   * closes near origin, no beeline segments or BL hints, bounded road reuse, and
   * sane voice-hint indices/angles. {@code maxReusePct} is relaxed for same-way-back
   * loops which intentionally retrace roads.
   */
  static void assertValidLoop(OsmTrack track, String label, double maxReusePct) {
    org.junit.Assert.assertNotNull(label + ": no track", track);
    java.util.List<OsmPathElement> nodes = track.nodes;
    org.junit.Assert.assertTrue(label + ": degenerate loop (" + nodes.size() + " nodes)",
      nodes.size() >= 10);

    int closing = nodes.get(0).calcDistance(nodes.get(nodes.size() - 1));
    org.junit.Assert.assertTrue(label + ": loop does not close, gap " + closing + "m",
      closing <= 100);

    int total = 0, reused = 0, maxSeg = 0;
    java.util.Set<Long> edges = new java.util.HashSet<>();
    long prevId = nodes.get(0).getIdFromPos();
    for (int i = 1; i < nodes.size(); i++) {
      long id = nodes.get(i).getIdFromPos();
      int d = nodes.get(i).calcDistance(nodes.get(i - 1));
      total += d;
      if (d > maxSeg) maxSeg = d;
      long edge = Math.min(prevId, id) * 1_000_003L + Math.max(prevId, id);
      if (!edges.add(edge)) reused += d;
      prevId = id;
    }
    org.junit.Assert.assertTrue(label + ": beeline segment " + maxSeg + "m", maxSeg <= 1500);
    double reusePct = total > 0 ? 100.0 * reused / total : 0;
    org.junit.Assert.assertTrue(label + ": road reuse " + (int) reusePct + "% > " + (int) maxReusePct + "%",
      reusePct <= maxReusePct);

    if (track.voiceHints != null) {
      for (VoiceHint h : track.voiceHints.list) {
        org.junit.Assert.assertTrue(label + ": voice hint index " + h.indexInTrack + " out of range",
          h.indexInTrack >= 0 && h.indexInTrack < nodes.size());
        org.junit.Assert.assertNotEquals(label + ": unexpected beeline hint", VoiceHint.BL, h.cmd);
        if (!h.isRoundabout()) {
          org.junit.Assert.assertTrue(label + ": voice hint angle " + h.angle + " out of [-180,180]",
            h.angle >= -180f && h.angle <= 180f);
        }
      }
    }
  }
}
