package btools.router;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * Shared setup for round-trip tests against the bundled Dreieich fixture
 * (generated by the map-creator test into build/resources, version-consistent
 * with misc/profiles2). No downloads required, so these run in CI.
 */
final class RoundTripFixture {

  static final int START_ILON = 188720000; // 8.72E (Dreieich)
  static final int START_ILAT = 140000000; // 50.0N

  private RoundTripFixture() {
  }

  static File projectDir() {
    try {
      return new File(".").getCanonicalFile().getParentFile();
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  static File segmentDir() {
    return new File(projectDir(), "brouter-map-creator/build/resources/test/tmp/segments");
  }

  static File profileFile(String name) {
    return new File(projectDir(), "misc/profiles2/" + name + ".brf");
  }

  /** Build and run a round-trip engine from the Dreieich origin. */
  static RoutingEngine engine(String profile, int direction, int radius) {
    List<OsmNodeNamed> wps = new ArrayList<>();
    OsmNodeNamed start = new OsmNodeNamed();
    start.name = "from";
    start.ilon = START_ILON;
    start.ilat = START_ILAT;
    wps.add(start);

    RoutingContext rc = new RoutingContext();
    rc.localFunction = profileFile(profile).getAbsolutePath();
    rc.startDirection = direction;
    rc.roundTripDistance = radius;
    rc.turnInstructionMode = 2; // generate voice hints so they can be validated

    RoutingEngine re = new RoutingEngine(null, null, segmentDir(), wps, rc,
      RoutingEngine.BROUTER_ENGINEMODE_ROUNDTRIP);
    re.quite = true;
    re.doRun(0);
    return re;
  }

  /** Convenience: the found track (may be null on failure). */
  static OsmTrack route(String profile, int direction, int radius) {
    return engine(profile, direction, radius).getFoundTrack();
  }
}
