package btools.router;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Structural invariants every generated round-trip loop must satisfy, exercised
 * against the bundled Dreieich fixture (generated by the map-creator test, so it
 * is always version-consistent with the profiles — no downloads required).
 * <p>
 * These are terrain-independent correctness properties (closure, no beelines,
 * bounded reuse, valid voice hints; see {@link RoundTripFixture#assertValidLoop}).
 * Distance-accuracy bands and shape quality are scale-dependent and live in the
 * gated, real-geography suite ({@link LoopQualityTest}).
 */
@RunWith(Parameterized.class)
public class RoundTripInvariantTest {

  private static final double MAX_REUSE_PCT = 30.0; // a loop, not an out-and-back

  @Parameterized.Parameter(0)
  public String profile;
  @Parameterized.Parameter(1)
  public int direction;
  @Parameterized.Parameter(2)
  public int radius;

  @Parameterized.Parameters(name = "{0}_dir{1}_r{2}")
  public static Collection<Object[]> data() {
    List<Object[]> params = new ArrayList<>();
    for (String profile : new String[]{"trekking", "fastbike", "gravel", "mtb"}) {
      for (int dir : new int[]{0, 90, 180, 270}) {
        // r1000/r1500 reliably produce real loops on the fixture; small-radius
        // degeneration is covered separately by RoundTripContractTest.
        for (int radius : new int[]{1000, 1500}) {
          params.add(new Object[]{profile, dir, radius});
        }
      }
    }
    return params;
  }

  @Test
  public void loopInvariants() {
    OsmTrack track = RoundTripFixture.route(profile, direction, radius);
    RoundTripFixture.assertValidLoop(track, profile + "_dir" + direction + "_r" + radius, MAX_REUSE_PCT);
  }
}
